#include <iostream>
#include <string>
#include <chrono>

#include "encoder.h"
#include "HV.h"

int main() {
    // Hardcoded test sequences
    /*std::string seq1 = "GACGAACGCTGGCGGCGTGCCTAACACATGCAAGTCGAACGGACGATGAGGAGCTTGCTCCTCAAAGTTAGTGGCGGACGGGTGAGTAACGCGTGAGTAACCTGCCTCAAAGAGGGGGATAACATTCGGAAACGAATGCTAATACCGCATAAGACTACGGTATCGCATGGTACAGTGGTCAAAGGAGCAATCCGCTTTGAGATGGACTCGCGTCCGATTAGCCAGTTGGCGGGGTAACGGCCCACCAAAGCTACGATCGGTAGCCGGACTGAGAGGTTGAACGGCCACATTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGAGGGATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGAGTGAGGGATGACGGTTTTCGGATTGTAAACCTCTGTCCTTGGTGACGAACACAATGACGGTAGCCGAGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCGAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGGAAGCAAGTCAGCGGTGAAATACATGAGCTTAACTCATGGACTGCCGTTGAAACTGTTTTTCTTGAGTGAAGTAGAGGTAGGCGGAATTCCGAGTGTAGCGGTGAAATGCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCCTACTGGGCTTTAACTGACGCTGAGGCTCGAAAGTGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACACTGTAAACGATGATTGCTAGGTGTGGGGGGTCTGACCCCTTCCGTGCCGCAGTTAACGCAATAAGCAATCCACCTGGGGAGTACGGCCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCAGTGGATTATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCGAGTGACGAGATTAGAGATAATCTTTTCCTTCGGGACACAAAGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCCATTAGTTGCTACGCAAGAGCACTCTAATGGGACCGCTATCGACAAGATGGAGGAAGGTGGGGACGACGTCAAATCATCATGCCCCTTATGACCTGGGCTACACACGTAATACAATGGCCGTTAACAGAGGGAAGCAAAGCCGCGAGGTGGAGCAAATCCCTAAAAACGGTCTCAGTTCGGATCGTAGGCTGCAACCCGCCTGCGTGAAGTTGGAATTGCTAGTAATCGCGGATCAGCATGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTTTGTAACACCCGAAGTCAGTAGTCTAACCGCAAGGAGGGCGCTGCCGAAGGTGGGATAAGCGACTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTC";
    std::string seq2 = "GACGAACGCTGGCGGCGTGCCTAACACATGCAAGTCGAACGGAGACAGTTCACCGAAATTGATGGAAGCTTGCTTTTGGATTTTTCACCGAGCTATCTTAGTGGCGGACGGGTGAGTAACGCGTGAGGAACCTGCCTTTCAGAGGGGGATAACGTTTGGAAACGAACGCTAATACCGCATAACACAATCGAGCGGCATCGCTTGATTGTCAAAGGAGCAATCCGCTGAAAGATGGACTCGCGTCTGATTAGATAGTTGGCGGGGTAACGGCCCACCAAGTCGACGATCAGTAGCCGGACTGAGAGGTTGAACGGCCACATTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGGATATTGCACAATGGAGGAAACTCTGATGCAGCAACGCCGCGTGAGGGAAGAAGGTTTTCGGATTGTAAACCTCTGTCCCTGATGACGAAGACAGTGACGGTAATCAGGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGGAGAGCAAGTCAGCGGTGAAATACATGGGCTTAACCCATGAACTGCCGTTGAAACTGTCCTTCTTGAGTGAAGTAGAGGCAGGCGGAATTCCGAGTGTAGCGGTGAAATGCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCCTGCTGGGCTTTTACTGACGCTGAGGCTCGAAAGTGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACACTGTAAACGATGATTGCTAGGTGTGGGGGGTCTGACCCCTTCCGTGCCGGAGTTAACACAATAAGCAATCCACCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCAGTGGAGTATGTGGTTTAATTCGACGCAACGCGAAGAACCTTACCAGGTCTTGACATCCAACTAACGAAGTAGAGATACATTAGGTGCCCTTCGGGGAAAGTTGAGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTGTCATTAGTTGCTACGCAAGAGCACTCTAATGAGACCGCCATCGACAAGATGGAGGAAGGTGGGGACGACGTCAAATCATCATGCCCTTTATGACCTGGGCTACACACGTACTACAATGGCCGTTAACAGAGGGAAGCAATACCGCGAGGAGGAGCAAACCCCTAAAAACGGTCTCAGTTCAGATTGCAGGCTGCAACTCGCCTGCATGAAGTCGGAATTGCTAGTAATCGCAGATCAGCATGCTGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGAGAGCCGGTAATACCCGAAGTCAGTAGCTTAACCGCAAGGAGAGCGCTGCCGAAGGTAGGATTGGCGATTGGGGTGAAGTCGTAACAAGGTAGCCGTAGGAGAACCTGCGGCTGGATCACCTC";
    std::string seq3 = "GACGAACGCTGGCGGCGTGCCTAACACATGCAAGTCGAACGAGCTGATTTCCTTCGGGAATGAAAGCGAGTGGCGGACGGGTGAGTAACGCGTGAGTAACCTGCCATTCAGAGGGGGATAACGTTTGGAAACAAACGCTAATACCGCATAAAGTGTATTTGCCGCATGACAAGATACACCAAAGGAGCAATCCGCTGTTTGATGGACTCGCGTCTGATTAGATAGTTGGTGAGGTAATGGCCCACCAAGTCGACGATCAGTAGCCGGACTGAGAGGTTGATCGGCCACATTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGAGGGATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGCGTGAGGGATGACGGTTTTCGGATTGTAAACCTCTGTTTTCAGTGAAGATAATGACATTAGCTGAAGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGGAGAGCAAGTCAGTGGTGAAATCTATGGGCTTAACCCATAAATTGCCGTTGAAACTGTTTTTCTTGAGTGAAGTAGAGGCAGGCGGAATTCCGAGTGTAGCGGTGAAATGCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCTTGCTGGGCTTTTACTGACGCTGAGGCTCGAAAGTGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACACTGTAAACGATGATTACTAGGTGTGGGGGGTCTGACCCCTTCCGTGCCGCAGTTAACGCAATAAGTAATCCACCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCAGTGGATTATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCGAGTGAACGGTTTAGAGATAAACCTTTCCTTCGGGACACAAAGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCCATTAGTTGCTACGCAAGAGCACTCTAATGGGACCGCTACCGACAAGGTGGAGGAAGGTGGGGACGACGTCAAATCATCATGCCCCTTATGACCTGGGCTACACACGTAATACAATGGTCGTCAACAGAGGGAAGCAAAACCGCAAGGCGGAGCAAACCCCTAAAAACGATCTCAGTTCGGATTGCAGGCTGCAACTCGCCTGTATGAAGTTGGAATTGCTAGTAATCGCGGATCAGCATGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTTTGTAACACCCGAAGTCATTAGTCTAACCGTAAGGAGGACGGTGCCGAAGGTGGGATAAGCGACTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTC";
    std::string seq4 = "CGTGAAGGAAGAAGGCTTTCGGGTTGTAAACTTCTTTTAAGAGGGAAGAGCAGAAGACGGTACCTCTTGAATAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCGTGTAGCCGGGCTGACAAGTCAGATGTGAAATCCGGAGGCTCAACCTCCGAACTGCATTTGAAACTGTTTCCCTTGAGTGTCGGAGAGGTAATCGGAATTCCTTGTGTAGCGGTGAAATGCGTAGATATTAGGAAGAACACCAGTGGCGAAGGCGGATGGCTGGACGACAACTGACGGTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCTGTAAACGATCAATACTAGGTGTGCGGGGACTGACCCCCTGCGTGCCGCAGCTAACGCAATAAGTATCCCACCTGGGGAGTACGATCGCAAGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTGGTTTAATTCGATGCAACGCGAAGAACCTTACCCAGGCTTGACATCTAGGGAACCTAACAGAGATGTTGGGGTGCTCTTCGGAGAACCCTAAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGTCCTTAGTAGCCAGCAGGTAAAGCTGGGCACTCTAGGGAGACCGCTTCGGTTAACGGAGAGGAAGGTGGGGACGACGTCAAGTCATCATGGCCCTTACGCCTGGGGCTACACACGTACTACAATGGTGCATACAAAGGGTTGCGAAACCGCGAGGTCAGGCTAATCCCAAAAAATGCATCTCAGTTCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCNNNNNNNNNNCGGGCCTTGTACACACCGCCCGTCACACCACGAAAGTTGGTTTTACCCGAAGCCGATGAGCTAACAGCAATGAGGCAATCGTCTACGGTAGGCCCGATGATTGGGGTGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGCTGGATCACCTCCTTTA";*/

    // Cache can hold a few entries for the test
    HVCache cache(10000);

    // Compute / fetch hypervectors
   /* const HV_16& hv1 = cache.get(seq1);
    const HV_16& hv2 = cache.get(seq2);
    const HV_16& hv3 = cache.get(seq3);
    const HV_16& hv4 = cache.get(seq4);

    // Compute similarities
    float sim11 = cosine(hv1, hv1);
    float sim12 = cosine(hv1, hv2);
    float sim13 = cosine(hv1, hv3);
    float sim23 = cosine(hv2, hv3);
    float sim14 = cosine(hv1, hv4);
    float sim24 = cosine(hv2, hv4);
    float sim34 = cosine(hv3, hv4);

    // Print results
    std::cout << "Similarity(seq1, seq1): " << sim11 << '\n';
    std::cout << "Similarity(seq1, seq2): " << sim12 << '\n';
    std::cout << "Similarity(seq1, seq3): " << sim13 << '\n';
    std::cout << "Similarity(seq2, seq3): " << sim23 << '\n';
    std::cout << "Similarity(seq1, seq4): " << sim14 << '\n';
    std::cout << "Similarity(seq2, seq4): " << sim24 << '\n';
    std::cout << "Similarity(seq3, seq4): " << sim34 << '\n';*/


    std::string ref = "GACGAACGCTGGCGGCGTGCCTAACACATGCAAGTCGAACGGACGATGAGGAGCTTGCTCCTCAAAGTTAGTGGCGGACGGGTGAGTAACGCGTGAGTAACCTGCCTCAAAGAGGGGGATAACATTCGGAAACGAATGCTAATACCGCATAAGACTACGGTATCGCATGGTACAGTGGTCAAAGGAGCAATCCGCTTTGAGATGGACTCGCGTCCGATTAGCCAGTTGGCGGGGTAACGGCCCACCAAAGCTACGATCGGTAGCCGGACTGAGAGGTTGAACGGCCACATTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGAGGGATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGAGTGAGGGATGACGGTTTTCGGATTGTAAACCTCTGTCCTTGGTGACGAACACAATGACGGTAGCCGAGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCGAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGGAAGCAAGTCAGCGGTGAAATACATGAGCTTAACTCATGGACTGCCGTTGAAACTGTTTTTCTTGAGTGAAGTAGAGGTAGGCGGAATTCCGAGTGTAGCGGTGAAATGCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCCTACTGGGCTTTAACTGACGCTGAGGCTCGAAAGTGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACACTGTAAACGATGATTGCTAGGTGTGGGGGGTCTGACCCCTTCCGTGCCGCAGTTAACGCAATAAGCAATCCACCTGGGGAGTACGGCCGCAAGGTTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCAGTGGATTATGTGGTTTAATTCGAAGCAACGCGAAGAACCTTACCAGGTCTTGACATCGAGTGACGAGATTAGAGATAATCTTTTCCTTCGGGACACAAAGACAGGTGGTGCATGGTTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCCATTAGTTGCTACGCAAGAGCACTCTAATGGGACCGCTATCGACAAGATGGAGGAAGGTGGGGACGACGTCAAATCATCATGCCCCTTATGACCTGGGCTACACACGTAATACAATGGCCGTTAACAGAGGGAAGCAAAGCCGCGAGGTGGAGCAAATCCCTAAAAACGGTCTCAGTTCGGATCGTAGGCTGCAACCCGCCTGCGTGAAGTTGGAATTGCTAGTAATCGCGGATCAGCATGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTTTGTAACACCCGAAGTCAGTAGTCTAACCGCAAGGAGGGCGCTGCCGAAGGTGGGATAAGCGACTGGGGTGAAGTCGTAACAAGGTAGCCGTATCGGAAGGTGCGGCTGGATCACCTC";
    std::string query = "GTGAAGTTGGAATTGCTAATCGCGGATCAGCATGCCGCGGTGAATACGTTCCCGGGCCTTTGTACACACCGCCCGTCACACCATGGAGTTTGTAACACCCGAAGTCAGTAGTCTAACCGCAA";
    std::cout << "\n\nTest 2";
    auto start = std::chrono::high_resolution_clock::now();
    std::cout << "\nCosine: " << std::to_string(cosine(cache.get(query), cache.get(ref)));
    auto stop = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);
    std::cout << "\nTime taken by operation 1: " << duration.count() << " microseconds" << std::endl;

     start = std::chrono::high_resolution_clock::now();
    cache.precompute(ref);
     stop = std::chrono::high_resolution_clock::now();
     duration = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);
    std::cout << "\nTime taken by operation 2: " << duration.count() << " microseconds" << std::endl;

     start = std::chrono::high_resolution_clock::now();
    std::cout << "\nSimilarity: " << std::to_string(cache.similarity(query, ref).score);
     stop = std::chrono::high_resolution_clock::now();
     duration = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);
    std::cout << "\nTime taken by operation 3: " << duration.count() << " microseconds" << std::endl;
    return 0;
}